spring:

  datasource:
    password: root
    url: jdbc:mysql://localhost:3306/rajeev
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: false
        format_sql: false
    show-sql: false
application:
     fileAccept: JPG, PNG, GIF
     
server.port: 10090

rabbitmq:
        host: localhost
        port: 5672
        username: guest
        password: guest


QC_TASK_START: QC_TASK_START
QC_STATS: QC_STATS
QC_LISTEN: QC_LISTEN